title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  main:
    title: "Main"
    description: |
      Primary button, to be used in most situations.
    width: "12em"
    fields:
      - name: 'btn'
        type: 'string'
        example: 'View Product'
      - name: 'link'
        type: 'string'
        example: '#'
  main-alt:
    title: "Main Alternate"
    description: |
      Alternate option to the main, to be used for actions that are of particular significance on a page ie. "Add to Cart".
    width: "12em"
    fields:
      - name: 'btn-alt'
        type: 'string'
        example: 'Learn More'
      - name: 'link'
        type: 'string'
        example: '#'
  solid:
    title: "Solid"
    description: |
      Solid colour button, used only for actions involving the checkout process. This includes the "Checkout" and "Place Order" buttons.
    width: "12em"
    fields:
      - name: 'solid'
        type: 'string'
        example: 'CHECKOUT'
      - name: 'link'
        type: 'string'
        example: '#'
    background: "--color-primary-light"
  icon-link:
    title: "Icon Link"
    description: |
      This icon link is used for specific icon instances when only an icon is need to signify a link tag, such as for social media or the cart.
    fields:
      - name: 'image'
        type: 'string'
        example: 'cart'
      - name: 'link'
        type: 'string'
        example: '#'
