title: "Sections"
description: |
  A display of some common sections on the site.

patterns:
  product-info:
    title: "Product Information"
    description: |
      The product information is displayed on every product page, to provide information for customers.
    fields:
      - name: 'image'
        type: 'string'
        example: 'honey/honey-alfalfa.png'
      - name: 'icon'
        type: 'string'
        example: 'alfalfa'
      - name: 'product-title'
        type: 'string'
        example: 'Honey with Alfalfa'
      - name: 'product-info'
        type: 'string'
        example: 'This delicious honey is a sweet treat for anyone who appreciates the tangy edge provided by the essense of alfalfa.'
      - name: 'product-price'
        type: 'string'
        example: '$8.00'
  subscribe:
    title: "Subscribe Banner"
    description: |
      This section is unique as it is the only banner on the site that does not use the hexagonal overlay card. It is to be used to encourage customers to sign up for a newsletter.
    height: 800
    fields:
      - name: 'image'
        type: 'string'
        example: 'honey/honey-alfalfa.png'
