title: "Sections"
description: |
  A display of some common sections on the site.

patterns:
  product-info:
    title: "Product Information"
    description: |
      The product information is displayed on every product page, to provide information for customers.
    fields:
      - name: data
        type: object
        data:
          source: "site.shop[0]"
          type: page
  subscribe:
    title: "Subscribe Banner"
    description: |
      This section is unique as it is the only banner on the site that does not use the hexagonal overlay card. It is to be used to encourage customers to sign up for a newsletter.
    height: 800
    fields:
      - name: 'image'
        type: 'string'
        example: 'honey/honey-alfalfa.png'
  cart-view:
    title: "Cart View Sidebar"
    description: |
      This sidebar appears on individual product pages, to indicate to customers what items they have already placed in their carts.
    fields:
      - name: 'icon'
        type: 'string'
        example: 'coffee'
      - name: 'product-name'
        type: 'string'
        example: 'Honey with Coffee'
      - name: 'product-quantity'
        type: 'string'
        example: '2 x $8.99'
      - name: 'product-name2'
        type: 'string'
        example: 'Honey with Orange'
      - name: 'product-quantity2'
        type: 'string'
        example: '1 x $8.99'
      - name: 'icon2'
        type: 'string'
        example: 'orange'
      - name: 'subtotal'
        type: 'string'
        example: '$26.97'
  cart-contents:
    title: "Cart Contents Sidebar"
    description: |
      This sidebar appears on the cart page, to show what is in the cart while the customer inputs their credit card and purchasing information.
    fields:
      - name: 'icon'
        type: 'string'
        example: 'coffee'
      - name: 'product-name'
        type: 'string'
        example: 'Honey with Coffee'
      - name: 'product-quantity'
        type: 'string'
        example: '2 x $8.99'
      - name: 'product-name2'
        type: 'string'
        example: 'Honey with Orange'
      - name: 'product-quantity2'
        type: 'string'
        example: '1 x $8.99'
      - name: 'icon2'
        type: 'string'
        example: 'orange'
      - name: 'subtotal'
        type: 'string'
        example: '$26.97'
      - name: 'total'
        type: 'string'
        example: '$44.97'
  shop-section-headers:
    title: "Shop Section Separators"
    description: |
      These section headers separate the shop contents to easily view everything, and to keep things organized.
    fields:
      - name: 'h3'
        type: 'string'
        example: 'Honey'
      - name: 'icon'
        type: 'string'
        example: 'honeypot-main'
      - name: 'id'
        type: 'string'
        example: 'honey'
  related:
    title: "Related Product List"
    description: |
      This section will not be properly displayed in this library, as it requires a product listing to show similar products, based on category. It will properly display on product pages, to suggest alternate products that are of a similar category.
